version: '3.4'

services:
  manage.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  manage.listings.processor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

